name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  rspec:
    name: rspec
    runs-on: ubuntu-latest
    container: ruby:2.6-slim

    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_DB: platform_test
          POSTGRES_PASSWORD: root

    env:
      RAILS_ENV: test
      TEST_PG_DATABASE: platform_test
      TEST_PG_USERNAME: root
      TEST_PG_PASSWORD: root
      TEST_PG_HOSTNAME: postgres
      TEST_PG_PORT: 5432
      SAUCE_ACCESS_KEY: '${{ secrets.SAUCE_ACCESS_KEY }}'
      SAUCE_TUNNEL_ID: 'sauce-ci-tunnel'
      SAUCE_USERNAME: '${{ secrets.SAUCE_USERNAME }}'
      USE_SAUCE: true

    steps:
      - name: Run Sauce Connect
        uses: saucelabs/sauce-connect-action@v1.1.1
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: sauce-ci-tunnel
          verbose: true

      - name: Install GH Actions Prerequisites
        run: apt-get update && apt-get install -y nodejs zstd git

      - name: Checkout repo
        uses: actions/checkout@master

      - name: Install System Packages
        run: apt-get update && apt-get install -y build-essential libxml2 libxml2-dev libxslt1.1 libxslt1-dev libpq5 libpq-dev git pkg-config

      - name: Install Dependencies
        run: gem install bundler && bundle install

      - name: start server
        run: |
          bin/rails server &
          curl http://localhost:3000
     # - name: Run tests
       # run: bundle exec rspec spec/features/hello_world_spec.rb
